import { StyleSheet } from "react-native";

export const createOrderFormStyles = (theme: any, isMobile: boolean) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: theme.background },
    header: {
      padding: 16,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      borderBottomWidth: 1,
      borderBottomColor: theme.borderColor,
    },
    backButton: {
      position: "absolute",
      left: 16,
      backgroundColor: theme.isDark ? theme.link : theme.primary,
      padding: 10,
      borderRadius: 10,
    },
    title: { color: theme.text, fontSize: 20, fontWeight: "bold" },
    scroll: { paddingBottom: 60 },
    form: {
      paddingHorizontal: isMobile ? 18 : 40,
      paddingTop: 20,
      width: isMobile ? "100%" : "70%",
      alignSelf: "center",
    },
    sectionTitle: {
      color: theme.text,
      fontSize: 15,
      fontWeight: "700",
      marginTop: 18,
      marginBottom: 10,
    },
    label: {
      color: theme.text,
      fontSize: 13,
      fontWeight: "600",
      marginBottom: 6,
      marginTop: 8,
    },
    input: {
      backgroundColor: theme.card,
      borderWidth: 1,
      borderColor: theme.inputBorder ?? theme.borderColor,
      borderRadius: 10,
      paddingHorizontal: 14,
      height: 48,
      color: theme.text,
    },
    multiline: { height: 90, paddingTop: 12, textAlignVertical: "top" },
    helper: { color: theme.textSecondary, fontSize: 12, marginTop: 4 },
    errorText: { color: theme.error, fontSize: 12, marginTop: 4 },

    pickerField: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      backgroundColor: theme.card,
      borderWidth: 1,
      borderColor: theme.inputBorder ?? theme.borderColor,
      borderRadius: 10,
      paddingHorizontal: 14,
      height: 50,
    },
    pickerText: { flex: 1, color: theme.text, fontSize: 15 },
    pickerPlaceholder: { flex: 1, color: theme.textSecondary, fontSize: 15 },

    // composição de veículos
    vehicleCard: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      backgroundColor: theme.card,
      borderWidth: 1,
      borderColor: theme.borderColor,
      borderRadius: 10,
      padding: 12,
      marginBottom: 8,
    },
    vehicleInfo: { flex: 1 },
    vehiclePlate: { color: theme.text, fontWeight: "700", fontSize: 14 },
    vehicleRole: { color: theme.textSecondary, fontSize: 12, marginTop: 2 },

    addBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      borderWidth: 1,
      borderStyle: "dashed",
      borderColor: theme.isDark ? theme.link : theme.primary,
      borderRadius: 10,
      paddingVertical: 12,
      marginTop: 4,
    },
    addBtnText: {
      color: theme.isDark ? theme.link : theme.primary,
      fontWeight: "700",
      fontSize: 14,
    },

    // chips (type_orders / segmented)
    chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 6 },
    chip: {
      paddingHorizontal: 12,
      paddingVertical: 7,
      borderRadius: 16,
      backgroundColor: theme.isDark ? "rgba(255,255,255,0.08)" : "#ECEEF1",
    },
    chipActive: { backgroundColor: theme.isDark ? theme.link : theme.primary },
    chipText: { color: theme.text, fontSize: 12, fontWeight: "600" },
    chipTextActive: { color: "#FFF", fontSize: 12, fontWeight: "600" },

    // AddInvoiceItems
    segmented: {
      flexDirection: "row",
      backgroundColor: theme.isDark ? "rgba(255,255,255,0.06)" : "#ECEEF1",
      borderRadius: 10,
      padding: 4,
      gap: 4,
      marginBottom: 12,
      flexWrap: "wrap",
    },
    segment: {
      flexGrow: 1,
      paddingVertical: 8,
      paddingHorizontal: 10,
      borderRadius: 8,
      alignItems: "center",
    },
    segmentActive: {
      backgroundColor: theme.isDark ? theme.link : theme.primary,
    },
    segmentText: { color: theme.text, fontSize: 12, fontWeight: "600" },
    segmentTextActive: { color: "#FFF", fontSize: 12, fontWeight: "600" },
    lookupRow: { flexDirection: "row", gap: 8, alignItems: "center" },
    lookupInput: {
      flex: 1,
      backgroundColor: theme.card,
      borderWidth: 1,
      borderColor: theme.inputBorder ?? theme.borderColor,
      borderRadius: 10,
      paddingHorizontal: 14,
      height: 48,
      color: theme.text,
    },
    lookupBtn: {
      backgroundColor: theme.isDark ? theme.link : theme.primary,
      borderRadius: 10,
      paddingHorizontal: 16,
      height: 48,
      alignItems: "center",
      justifyContent: "center",
    },
    lookupBtnText: { color: "#FFF", fontWeight: "700" },

    itemCard: {
      backgroundColor: theme.card,
      borderWidth: 1,
      borderColor: theme.borderColor,
      borderRadius: 12,
      padding: 12,
      marginTop: 10,
    },
    itemTop: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    itemLabel: { color: theme.text, fontWeight: "700", fontSize: 14 },
    itemSub: { color: theme.textSecondary, fontSize: 12, marginTop: 2 },
    trackingInput: {
      backgroundColor: theme.background,
      borderWidth: 1,
      borderColor: theme.inputBorder ?? theme.borderColor,
      borderRadius: 8,
      paddingHorizontal: 12,
      height: 40,
      color: theme.text,
      marginTop: 8,
    },
    lockTag: {
      color: "#2E7D32",
      fontSize: 11,
      fontWeight: "700",
    },

    // submit / delete
    button: {
      backgroundColor: theme.isDark ? theme.link : theme.primary,
      borderRadius: 12,
      height: 52,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 24,
    },
    buttonText: { color: "#FFF", fontWeight: "700", fontSize: 16 },
    deleteBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      borderRadius: 12,
      height: 48,
      backgroundColor: theme.error,
      marginTop: 12,
    },
    deleteBtnText: { color: "#FFF", fontWeight: "700", fontSize: 15 },

    lockedBanner: {
      backgroundColor: theme.isDark ? "rgba(239,68,68,0.15)" : "#fdecea",
      borderRadius: 10,
      padding: 12,
      marginBottom: 8,
    },
    lockedText: { color: theme.error, fontSize: 13, fontWeight: "600" },
    infoBanner: {
      backgroundColor: theme.isDark ? "rgba(239,108,0,0.15)" : "#fff4e5",
      borderRadius: 10,
      padding: 12,
      marginBottom: 8,
    },
    infoText: { color: "#EF6C00", fontSize: 13, fontWeight: "600" },

    removeBtn: { padding: 6 },
  });
